.\"
.\" Copyright (c) 2019 Marc Espie <espie@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt UNWEBP 1
.Os
.Sh NAME
.Nm unwebp
.Nd convert webp files into gif or png
.Sh SYNOPSIS
.Nm unwebp
.Op Fl defv
.Ar file ...
.Sh DESCRIPTION
.Nm
converts webp files into something decent like gif or png.
Each
.Ar file
passed on the command line is stripped of a .webp extension
and converted into a file with the proper .gif or .png extension,
depending on whether it's an animated webp or a static image.
.Pp
Non webp files will be left alone, but
.Nm
will exit with an error at the end.
.Pp
Options are:
.Bl -tag -width key
.It Fl d
Delete the source webp file once it's been successfully converted.
Also delete it if conversion was already done.
.It Fl e
Show the resulting filenames
.It Fl f
Force conversion.
By default,
.Nm
will skip files where the result already exists.
.It Fl v
Show details of the conversion.
.El
.Sh SEE ALSO
.Xr gm 1 ,
.Xr webpmux 1
.Sh AUTHORS
.An Marc Espie Aq Mt espie@openbsd.org
